import random

from ViennaRNA import RNA


def reversed_seq(seq):
    return reversed(seq)


def complementary_seq(seq):
    complement = {
        "A": "U",
        "U": "A",
        "G": "C",
        "C": "G",
        "a": "u",
        "u": "a",
        "g": "c",
        "c": "g",
    }
    res = "".join(complement[base] for base in seq)
    return res

def generate_random_seq(length, probs={'A':0.25, 'U':0.25, 'C':0.25, 'G':0.25}):
    bases = list(probs.keys())
    weights = list(probs.values())

    res = "".join(random.choices(bases, weights=weights, k=length))
    return res



def get_rnafold_parameters(seq):

    fc = RNA.fold_compound(seq)

    ss, mfe = fc.mfe()
    fc.exp_params_rescale(mfe)

    fc.pf()

    freq_mfe = fc.pr_structure(ss)

    div = fc.mean_bp_distance()

    return ss, mfe, freq_mfe, div


def mutate_sequence(seq, from_base, to_base, prob=0.5):
    new_seq = []
    for base in seq:
        if base == from_base and random.random() < prob:
            new_seq.append(to_base)
        else:
            new_seq.append(base)
    return "".join(new_seq)


if __name__ == '__main__':
    a = get_rnafold_parameters('AAGCGUGCUCAUCACAUCUCGCGCACUUUUGUGAAACUCUCUUCUGGGCCACUCUUCUUCGGAAGAGUGGCCCAGAAGAGAGUUUCACUUUUGUCACGACUUCCUCAAUGUGCCUCUUAACGUGAGGCACAUUGAGGAAGUCGGUUUUCGCUAGGAUUUGUUAGGUUUCCCGUUGUUCGCAACGGGAAACCUAACAAAUCCUAGCGUUUUGCUAGGAUUUGUUAGGUUUCCCGCUUGAAACCGCUACAAGCGGGAAACCUAACAAAUCCUAGCUUUUCCGACUUCCUCAAUGUGCCUCACGUUAAGAGGCACAUUGAGGAAGUCGUGACUUUUGUGCGCGAGAUGUGAUGAGCACGCUUAAGCGUGGCCCAGAAGAGAGUUUCACUUUUGCGACCCGACCUGCUUAGCCUCGCUUGAAAGCGGUACAAGCGAGGCUAAGCAGGUCGGGUCGCUUUUGUCACGACUUCCUCAAUGUGCCUCUUCGCAAGAAGAGGCACAUUGAGGAAGUCGUGACUUUUGUGAAACUCUCUUCUGGGCCACGCUU')
    print(a[-1], a[-2])
    a = get_rnafold_parameters('AAGCGUGCUCAUCACAUCUCGCGCACUUUUCUGUCACGACUUCCUCAAUGUGCCUUCUUCGGAAGGCACAUUGAGGAAGUCGUGACAGUUUUCUGAAACUCUCUUCUGGGCCACUCUUAAGUGGCCCAGAAGAGAGUUUCAUCGUUUUGUGAAACUCUCUUCUGGGCCACGCUUCUUCGGAAGCGUGGCCCAGAAGAGAGUUUCACUUUUGUCAUCAGAAGCCACCACAUGGGCUUAAGCGGGAAACCUAACAAAUCCUAGCUUUUCGCUAGGAUUUGUUAGGUUUCCCGUUGGCAACAACGGGAAACCUAACAAAUCCUAGCGUUUUGAUGAAACUCUCUUCUGGGCCACCUUCAAACCGCUAGAAGGUGGCCCAGAAGAGAGUUUCAUCUUUUGCUAGGAUUUGUUAGGUUUCCCGCUUAAGCCCAUGUGGUGGCUUCUGAUGACUUUUCGAUGAAACUCUCUUCUGGGCCACUUAAGAGUGGCCCAGAAGAGAGUUUCAGUUUUGUGCGCGAGAUGUGAUGAGCACGCUUAACGUGAGGCACAUUGAGGAAGUCGGUUUUGUACGACCCGACCUGCUUAGCCGCUUGAAAGCGGUACAAGCGGCUAAGCAGGUCGGGUCGUACUUUUGCGACCCGACCUGCUUAGCCUCGCUUCUCCGGAAGCGAGGCUAAGCAGGUCGGGUCGCUUUUCCGACUUCCUCAAUGUGCCUCACGUU')
    print(a[-1], a[-2])


